// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"time"

	uuid "github.com/google/uuid"
)

type Event struct {
	ID        string
	Name      string
	PayerID   uuid.UUID
	Amount    int32
	EventDate time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Payment struct {
	EventID  string
	DebtorID uuid.UUID
	Amount   int32
}

type User struct {
	ID        uuid.UUID
	Name      string
	Avatar    string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
