// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        string
	Name      string
	Amount    int32
	EventDate time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Payment struct {
	ID       string
	EventID  *string
	PayerID  pgtype.UUID
	DebtorID pgtype.UUID
	Amount   int32
}

type User struct {
	ID        uuid.UUID
	Name      string
	Avatar    string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
