// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"time"
)

type Event struct {
	ID        string
	Name      string
	EventAt   time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}
