version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependancy-name: *
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
