// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"

	uuid "github.com/google/uuid"
)

type Event struct {
	ID        string
	Name      string
	Amount    int32
	EventDate time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type EventPayment struct {
	EventID   string
	PaymentID string
}

type Payment struct {
	ID        string
	PayerID   uuid.UUID
	DebtorID  uuid.UUID
	Amount    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Avatar    string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
