version: "3"

tasks:
  db:migrate:
    desc: "データベースマイグレーションを実行"
    dotenv:
      - "backend/.env"
    dir: backend
    cmds:
      - |
        atlas schema apply \
          --url $DSN \
          --dev-url "docker://postgres" \
          --to "file://sql/schema.sql"
  db:seed:
    desc: "シードデータを投入"
    dotenv:
      - "backend/.env"
    dir: backend
    cmds:
      - |
        psql $DSN \
          -f sql/init.sql
  sqlc:gen:
    desc: "sqlcでクエリコードを生成"
    dir: backend
    cmds:
      - sqlc generate
  api:gen:
    desc: "OpenAPIから型とサーバーコードを生成"
    dir: backend
    cmds:
      - |
        oapi-codegen -generate "types" \
          -package api \
          ./openapi.yaml \
          > ./internal/presentation/api/types.gen.go
      - |
        oapi-codegen -generate "server" \
          -package api ./openapi.yaml \
          > ./internal/presentation/api/server.gen.go
  api:test:
    desc: "テストを実行"
    dir: backend
    cmds:
      - go test -race ./...
  mock:gen:
    desc: "mockgenでモックを生成"
    dir: backend
    cmds:
      - |
        mockgen -source=internal/domain/user.go \
          -destination=internal/usecase/test/mockUserRepository.gen.go \
          -package=usecase_test
      - |
        mockgen -source=internal/domain/lending.go \
          -destination=internal/usecase/test/mockLendingEventRepository.gen.go \
          -package=usecase_test
      - |
        mockgen -source=internal/domain/payer.go \
          -destination=internal/usecase/test/mockPayerRepository.gen.go \
          -package=usecase_test
      - |
        mockgen -source=internal/domain/credit.go \
          -destination=internal/usecase/test/mockCreditRepository.gen.go \
          -package=usecase_test
      - |
        mockgen -source=internal/presentation/api/handler/lending.go \
          -destination=internal/presentation/api/handler/test/mockLendingUseCase.gen.go \
          -package=handler_test
      - |
        mockgen -source=internal/presentation/api/handler/credit.go \
          -destination=internal/presentation/api/handler/test/mockCreditUseCase.gen.go \
          -package=handler_test
  api:dev:
    desc: "APIサーバーを起動(ホットリロード)"
    dotenv:
      - "backend/.env"
    dir: backend
    cmds:
      - air
  api:docs:
    desc: "OpenAPIドキュメントをプレビュー"
    dir: backend
    cmds:
      - npx @redocly/cli@latest preview --product redoc -p 8080
  web:dev:
    desc: "Webサーバーを起動(ホットリロード)"
    dir: frontend
    cmds:
      - pnpm dev
