version: "3"

tasks:
  localstack:init:
    desc: "LocalStackのリソースを初期化（DynamoDB, S3）"
    env:
      AWS_ENDPOINT_URL: http://localhost:4566
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-1
    cmds:
      # DynamoDB: Sessions table
      - |
        aws dynamodb create-table \
          --table-name local-datti-sessions \
          --attribute-definitions AttributeName=sessionId,AttributeType=S \
          --key-schema AttributeName=sessionId,KeyType=HASH \
          --billing-mode PAY_PER_REQUEST \
          --endpoint-url $AWS_ENDPOINT_URL
      - |
        aws dynamodb update-time-to-live \
          --table-name local-datti-sessions \
          --time-to-live-specification Enabled=true,AttributeName=expiresAt \
          --endpoint-url $AWS_ENDPOINT_URL
      # S3: Profile images bucket
      - aws s3 mb s3://local-datti-avatar --endpoint-url $AWS_ENDPOINT_URL
      - |
        aws s3api put-bucket-policy \
          --bucket local-datti-avatar \
          --endpoint-url $AWS_ENDPOINT_URL \
          --policy '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "PublicReadGetObject",
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::local-datti-avatar/*"
              }
            ]
          }'
  postgres:migrate:
    desc: "Postgresのマイグレーションを実行"
    env:
      POSTGRES_DSN: postgres://postgres:password@localhost:5432/datti?sslmode=disable
    dir: backend
    cmds:
      - |
        atlas schema apply \
          --url $POSTGRES_DSN \
          --dev-url "docker://postgres" \
          --to "file://sql/schema.sql"
  postgres:seed:
    desc: "Postgresにシードデータを投入"
    dotenv:
      - "backend/.env"
    dir: backend
    env:
      POSTGRES_DSN: postgres://postgres:password@localhost:5432/datti?sslmode=disable
    cmds:
      - |
        psql $POSTGRES_DSN \
          -f sql/init.sql
  sqlc:gen:
    desc: "sqlcでクエリコードを生成"
    dir: backend
    cmds:
      - sqlc generate
  api:gen-interface:
    desc: "OpenAPIから型とサーバーコードを生成"
    dir: backend
    cmds:
      - |
        oapi-codegen -generate "types" \
          -package api \
          ./openapi.yaml \
          > ./internal/presentation/api/types.gen.go
      - |
        oapi-codegen -generate "server" \
          -package api ./openapi.yaml \
          > ./internal/presentation/api/server.gen.go
  api:gen-mock:
    desc: "mockgenでモックを生成"
    dir: backend
    cmds:
      - |
        mockgen -source=internal/domain/user.go \
          -destination=internal/usecase/test/mockUserRepository.gen.go \
          -package=usecase_test
      - |
        mockgen -source=internal/domain/lending.go \
          -destination=internal/usecase/test/mockLendingEventRepository.gen.go \
          -package=usecase_test
      - |
        mockgen -source=internal/domain/payer.go \
          -destination=internal/usecase/test/mockPayerRepository.gen.go \
          -package=usecase_test
      - |
        mockgen -source=internal/domain/credit.go \
          -destination=internal/usecase/test/mockCreditRepository.gen.go \
          -package=usecase_test
      - |
        mockgen -source=internal/presentation/api/handler/lending.go \
          -destination=internal/presentation/api/handler/test/mockLendingUseCase.gen.go \
          -package=handler_test
      - |
        mockgen -source=internal/presentation/api/handler/credit.go \
          -destination=internal/presentation/api/handler/test/mockCreditUseCase.gen.go \
          -package=handler_test
  api:test:
    desc: "APIのテストを実行"
    dir: backend
    cmds:
      - go test -race ./...
  api:dev:
    desc: "APIの開発サーバーを起動"
    dotenv:
      - "backend/.env"
    dir: backend
    cmds:
      - air
  api:docs:
    desc: "OpenAPIドキュメントをプレビュー"
    dir: backend
    cmds:
      - npx @redocly/cli@latest preview --product redoc -p 8080
  web:dev:
    desc: "Webの開発サーバーを起動"
    dir: frontend
    cmds:
      - pnpm dev
