# fly.toml app configuration file generated for datti-api-prod on 2024-01-30T23:53:31+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datti-api-prod"
primary_region = "nrt"

[build]
  image = "registry.fly.io/datti-api-prod:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
