version: '3'
dotenv:
  - '.env'
tasks:
  db-migrate:
    cmds:
      - |
        atlas schema apply \
          --url $DSN \
          --dev-url "docker://postgres" \
          --to "file://sql/schema.sql"
  db-seed:
    cmds:
      - |
        psql $DSN \
          -f sql/init.sql
  gen-sqlc:
    cmds:
      - go tool sqlc generate
  gen-types:
    cmds:
      - |
        go tool oapi-codegen -generate "types" \
          -package api \
          ../../docs/openapi/tsp-output/@typespec/openapi3/openapi.yaml \
          > ./internal/presentation/api/types.gen.go
  gen-server:
    cmds:
      - |
        go tool oapi-codegen -generate "server" \
          -package api ../../docs/openapi/tsp-output/@typespec/openapi3/openapi.yaml \
          > ./internal/presentation/api/server.gen.go
  test:
    cmds:
      - go test -race ./...
  gen-mocks:
    desc: "Generate mocks using mockgen"
    cmds:
      - |
        go tool mockgen -source=internal/domain/user.go \
          -destination=internal/usecase/test/mockUserRepository.gen.go \
          -package=usecase_test
      - |
        go tool mockgen -source=internal/domain/lendingEvent.go \
          -destination=internal/usecase/test/mockLendingEventRepository.gen.go \
          -package=usecase_test
      - |
        go tool mockgen -source=internal/domain/payer.go \
          -destination=internal/usecase/test/mockPayerRepository.gen.go \
          -package=usecase_test
      - |
        go tool mockgen -source=internal/domain/credit.go \
          -destination=internal/usecase/test/mockCreditRepository.gen.go \
          -package=usecase_test
      - |
        go tool mockgen -source=internal/presentation/api/handler/lending.go \
          -destination=internal/presentation/api/handler/test/mockLendingUseCase.gen.go \
          -package=handler_test
