version: '3'
dotenv:
  - '.env'
tasks:
  gen-sqlc:
    cmds:
      - sqlc generate
  migrate-db:
    cmds:
      - |
        atlas schema apply \
          --url $DSN \
          --dev-url "docker://postgres" \
          --to "file://sql/schema.sql"
  test:
    cmds:
      - go test -race ./...
  gen-type:
    cmds:
      - |
        oapi-codegen -generate "types" \
          -package api \
          ../../docs/openapi/tsp-output/@typespec/openapi3/openapi.yaml \
          > ./internal/presentation/api/types.gen.go
  gen-server:
    cmds:
      - |
        oapi-codegen -generate "server" \
          -package api ../../docs/openapi/tsp-output/@typespec/openapi3/openapi.yaml \
          > ./internal/presentation/api/server.gen.go
  gen-mocks:
    desc: "Generate mocks using mockgen"
    cmds:
      - |
        mockgen -source=internal/domain/user.go \
          -destination=internal/usecase/test/mockUserRepository.gen.go \
          -package=usecase_test
      - |
        mockgen -source=internal/domain/lendingEvent.go \
          -destination=internal/usecase/test/mockLendingEventRepository.gen.go \
          -package=usecase_test
      - |
        mockgen -source=internal/domain/payer.go \
          -destination=internal/usecase/test/mockPayerRepository.gen.go \
          -package=usecase_test
      - |
        mockgen -source=internal/presentation/api/handler/lendingEvent.go \
          -destination=internal/presentation/api/handler/test/mockLendingEventUseCase.gen.go \
          -package=handler_test
