services:
  app:
    container_name: datti-api
    image: mcr.microsoft.com/devcontainers/go:1.22-bookworm
    environment:
      - TZ=Asia/Tokyo
    tty: true
    volumes:
      - type: bind
        source: ../../../
        target: /workspaces/datti
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: atlas_db
      TZ: Asia/Tokyo
    volumes:
      - type: bind
        source: ./db/data
        target: /var/lib/postgresql/data
