services:
  app:
    container_name: datti-api
    image: mcr.microsoft.com/devcontainers/go:1.22-bookworm
    environment:
      - TZ=Asia/Tokyo
    tty: true
    volumes:
      - type: bind
        source: ../../../
        target: /workspaces/datti
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: datti
      TZ: Asia/Tokyo
    volumes:
      - type: bind
        source: ./db/data
        target: /var/lib/postgresql/data
  atlas_db:
    container_name: atlas_db
    image: postgres:15
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: atlas
      TZ: Asia/Tokyo
    volumes:
      - type: bind
        source: ./atlas_db/data
        target: /var/lib/postgresql/data
