name: 機能要望・バックログ
description: 機能要望・バックログを挙げるissueテンプレート
labels:
  - enhancement
body:
  - type: input
    attributes:
      label: 対象ページ

  - type: textarea
    attributes:
      label: 詳細内容
      description: |
        - 詳細な要望内容がわかるよう, できるだけスクリーンショット等のエビデンスを添付して記載してください
    validations:
      required: true

  - type: textarea
    attributes:
      label: 対応方針
      description: 対応方針が決まっている場合は記載してください
