name: リファクタリング
description: リファクタリングを挙げるissueテンプレート
labels:
  - refactor
body:
  - type: input
    attributes:
      label: 対象機能・コンポーネント

  - type: textarea
    attributes:
      label: 詳細内容
      description: |
        - 詳細なリファクタ内容がわかるよう, できるだけスクリーンショット等のエビデンスを添付して記載してください
    validations:
      required: true

  - type: textarea
    attributes:
      label: 対応方針
      description: 対応方針が決まっている場合は記載してください
