// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HealthCheckResponseStatus.
const (
	Ok HealthCheckResponseStatus = "ok"
)

// BorrowingGetAllResponse defines model for Borrowing.GetAllResponse.
type BorrowingGetAllResponse struct {
	Amount    uint64    `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
	EventDate time.Time `json:"eventDate"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// Credit defines model for Credit.
type Credit struct {
	Amount int64  `json:"amount"`
	UserId string `json:"userId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// HealthCheckResponse defines model for Health.CheckResponse.
type HealthCheckResponse struct {
	Status    HealthCheckResponseStatus `json:"status"`
	Timestamp time.Time                 `json:"timestamp"`
}

// HealthCheckResponseStatus defines model for HealthCheckResponse.Status.
type HealthCheckResponseStatus string

// LendingCreateRequest defines model for Lending.CreateRequest.
type LendingCreateRequest struct {
	Amount    uint64              `json:"amount"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Name      string              `json:"name"`
}

// LendingCreateResponse defines model for Lending.CreateResponse.
type LendingCreateResponse struct {
	Amount    uint64              `json:"amount"`
	CreatedAt time.Time           `json:"createdAt"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Id        string              `json:"id"`
	Name      string              `json:"name"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// LendingDebtParmam defines model for Lending.DebtParmam.
type LendingDebtParmam struct {
	Amount uint64 `json:"amount"`
	UserId string `json:"userId"`
}

// LendingGetAllResponse defines model for Lending.GetAllResponse.
type LendingGetAllResponse struct {
	Amount    uint64              `json:"amount"`
	CreatedAt time.Time           `json:"createdAt"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Id        string              `json:"id"`
	Name      string              `json:"name"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// LendingGetResponse defines model for Lending.GetResponse.
type LendingGetResponse struct {
	Amount    uint64              `json:"amount"`
	CreatedAt time.Time           `json:"createdAt"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Id        string              `json:"id"`
	Name      string              `json:"name"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// LendingUpdateRequest defines model for Lending.UpdateRequest.
type LendingUpdateRequest struct {
	Amount    uint64              `json:"amount"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Name      string              `json:"name"`
}

// LendingUpdateResponse defines model for Lending.UpdateResponse.
type LendingUpdateResponse struct {
	Amount    uint64              `json:"amount"`
	CreatedAt time.Time           `json:"createdAt"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Id        string              `json:"id"`
	Name      string              `json:"name"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// RepaymentCreateRequest defines model for Repayment.CreateRequest.
type RepaymentCreateRequest struct {
	Amount   uint64 `json:"amount"`
	DebtorId string `json:"debtorId"`
}

// RepaymentCreateResponse defines model for Repayment.CreateResponse.
type RepaymentCreateResponse struct {
	Amount    uint64    `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
	DebtorId  string    `json:"debtorId"`
	Id        string    `json:"id"`
	PayerId   string    `json:"payerId"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// LendingCreateJSONRequestBody defines body for LendingCreate for application/json ContentType.
type LendingCreateJSONRequestBody = LendingCreateRequest

// LendingUpdateJSONRequestBody defines body for LendingUpdate for application/json ContentType.
type LendingUpdateJSONRequestBody = LendingUpdateRequest

// RepaymentCreateJSONRequestBody defines body for RepaymentCreate for application/json ContentType.
type RepaymentCreateJSONRequestBody = RepaymentCreateRequest
