// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HealthCheckResponseStatus.
const (
	Ok HealthCheckResponseStatus = "ok"
)

// AuthSignupRequest defines model for Auth.SignupRequest.
type AuthSignupRequest struct {
	Avatar string `json:"avatar"`
	Email  string `json:"email"`
	Name   string `json:"name"`
}

// AuthSignupResponse defines model for Auth.SignupResponse.
type AuthSignupResponse struct {
	Avatar string `json:"avatar"`
	Email  string `json:"email"`
	Id     string `json:"id"`
	Name   string `json:"name"`
}

// BorrowingGetAllResponse defines model for Borrowing.GetAllResponse.
type BorrowingGetAllResponse struct {
	Amount    uint64    `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
	EventDate time.Time `json:"eventDate"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// BorrowingGetResponse defines model for Borrowing.GetResponse.
type BorrowingGetResponse struct {
	Amount    uint64    `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
	EventDate time.Time `json:"eventDate"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// Credit defines model for Credit.
type Credit struct {
	Amount int64  `json:"amount"`
	UserId string `json:"userId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// GroupAddMemberRequest defines model for Group.AddMemberRequest.
type GroupAddMemberRequest struct {
	UserId string `json:"userId"`
}

// GroupCreateRequest defines model for Group.CreateRequest.
type GroupCreateRequest struct {
	Name string `json:"name"`
}

// GroupCreateResponse defines model for Group.CreateResponse.
type GroupCreateResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy string    `json:"createdBy"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// GroupGetAllResponse defines model for Group.GetAllResponse.
type GroupGetAllResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy string    `json:"createdBy"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// GroupGetResponse defines model for Group.GetResponse.
type GroupGetResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy string    `json:"createdBy"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// GroupMemberResponse defines model for Group.MemberResponse.
type GroupMemberResponse struct {
	Avatar string `json:"avatar"`
	Email  string `json:"email"`
	Id     string `json:"id"`
	Name   string `json:"name"`
}

// GroupUpdateRequest defines model for Group.UpdateRequest.
type GroupUpdateRequest struct {
	Name string `json:"name"`
}

// GroupUpdateResponse defines model for Group.UpdateResponse.
type GroupUpdateResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy string    `json:"createdBy"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// HealthCheckResponse defines model for Health.CheckResponse.
type HealthCheckResponse struct {
	Status    HealthCheckResponseStatus `json:"status"`
	Timestamp time.Time                 `json:"timestamp"`
}

// HealthCheckResponseStatus defines model for HealthCheckResponse.Status.
type HealthCheckResponseStatus string

// LendingCreateRequest defines model for Lending.CreateRequest.
type LendingCreateRequest struct {
	Amount    uint64              `json:"amount"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Name      string              `json:"name"`
}

// LendingCreateResponse defines model for Lending.CreateResponse.
type LendingCreateResponse struct {
	Amount    uint64              `json:"amount"`
	CreatedAt time.Time           `json:"createdAt"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Id        string              `json:"id"`
	Name      string              `json:"name"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// LendingDebtParmam defines model for Lending.DebtParmam.
type LendingDebtParmam struct {
	Amount uint64 `json:"amount"`
	UserId string `json:"userId"`
}

// LendingGetAllResponse defines model for Lending.GetAllResponse.
type LendingGetAllResponse struct {
	Amount    uint64              `json:"amount"`
	CreatedAt time.Time           `json:"createdAt"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Id        string              `json:"id"`
	Name      string              `json:"name"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// LendingGetResponse defines model for Lending.GetResponse.
type LendingGetResponse struct {
	Amount    uint64              `json:"amount"`
	CreatedAt time.Time           `json:"createdAt"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Id        string              `json:"id"`
	Name      string              `json:"name"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// LendingUpdateRequest defines model for Lending.UpdateRequest.
type LendingUpdateRequest struct {
	Amount    uint64              `json:"amount"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Name      string              `json:"name"`
}

// LendingUpdateResponse defines model for Lending.UpdateResponse.
type LendingUpdateResponse struct {
	Amount    uint64              `json:"amount"`
	CreatedAt time.Time           `json:"createdAt"`
	Debts     []LendingDebtParmam `json:"debts"`
	EventDate time.Time           `json:"eventDate"`
	Id        string              `json:"id"`
	Name      string              `json:"name"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// RepaymentCreateRequest defines model for Repayment.CreateRequest.
type RepaymentCreateRequest struct {
	Amount   uint64 `json:"amount"`
	DebtorId string `json:"debtorId"`
}

// RepaymentCreateResponse defines model for Repayment.CreateResponse.
type RepaymentCreateResponse struct {
	Amount    uint64    `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
	DebtorId  string    `json:"debtorId"`
	Id        string    `json:"id"`
	PayerId   string    `json:"payerId"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// RepaymentGetAllResponse defines model for Repayment.GetAllResponse.
type RepaymentGetAllResponse struct {
	Amount    uint64    `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
	DebtorId  string    `json:"debtorId"`
	Id        string    `json:"id"`
	PayerId   string    `json:"payerId"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// RepaymentGetResponse defines model for Repayment.GetResponse.
type RepaymentGetResponse struct {
	Amount    uint64    `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
	DebtorId  string    `json:"debtorId"`
	Id        string    `json:"id"`
	PayerId   string    `json:"payerId"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// RepaymentUpdateRequest defines model for Repayment.UpdateRequest.
type RepaymentUpdateRequest struct {
	Amount uint64 `json:"amount"`
}

// RepaymentUpdateResponse defines model for Repayment.UpdateResponse.
type RepaymentUpdateResponse struct {
	Amount    uint64    `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
	DebtorId  string    `json:"debtorId"`
	Id        string    `json:"id"`
	PayerId   string    `json:"payerId"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// UserGetResponse defines model for User.GetResponse.
type UserGetResponse struct {
	Avatar string `json:"avatar"`
	Email  string `json:"email"`
	Id     string `json:"id"`
	Name   string `json:"name"`
}

// UserSearchResponse defines model for User.SearchResponse.
type UserSearchResponse struct {
	Avatar string `json:"avatar"`
	Email  string `json:"email"`
	Id     string `json:"id"`
	Name   string `json:"name"`
}

// UserUpdateRequest defines model for User.UpdateRequest.
type UserUpdateRequest struct {
	Avatar string `json:"avatar"`
	Name   string `json:"name"`
}

// UserSearchParams defines parameters for UserSearch.
type UserSearchParams struct {
	Name  *string `form:"name,omitempty" json:"name,omitempty"`
	Email *string `form:"email,omitempty" json:"email,omitempty"`
	Limit *int32  `form:"limit,omitempty" json:"limit,omitempty"`
}

// AuthSignupJSONRequestBody defines body for AuthSignup for application/json ContentType.
type AuthSignupJSONRequestBody = AuthSignupRequest

// GroupCreateJSONRequestBody defines body for GroupCreate for application/json ContentType.
type GroupCreateJSONRequestBody = GroupCreateRequest

// GroupUpdateJSONRequestBody defines body for GroupUpdate for application/json ContentType.
type GroupUpdateJSONRequestBody = GroupUpdateRequest

// LendingCreateJSONRequestBody defines body for LendingCreate for application/json ContentType.
type LendingCreateJSONRequestBody = LendingCreateRequest

// LendingUpdateJSONRequestBody defines body for LendingUpdate for application/json ContentType.
type LendingUpdateJSONRequestBody = LendingUpdateRequest

// GroupAddMemberJSONRequestBody defines body for GroupAddMember for application/json ContentType.
type GroupAddMemberJSONRequestBody = GroupAddMemberRequest

// RepaymentCreateJSONRequestBody defines body for RepaymentCreate for application/json ContentType.
type RepaymentCreateJSONRequestBody = RepaymentCreateRequest

// RepaymentUpdateJSONRequestBody defines body for RepaymentUpdate for application/json ContentType.
type RepaymentUpdateJSONRequestBody = RepaymentUpdateRequest

// UserUpdateJSONRequestBody defines body for UserUpdate for application/json ContentType.
type UserUpdateJSONRequestBody = UserUpdateRequest
