// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/lending.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/lending.go -destination=internal/usecase/test/mockLendingEventRepository.gen.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/haebeal/datti/internal/domain"
	ulid "github.com/oklog/ulid/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockLendingEventRepository is a mock of LendingEventRepository interface.
type MockLendingEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLendingEventRepositoryMockRecorder
	isgomock struct{}
}

// MockLendingEventRepositoryMockRecorder is the mock recorder for MockLendingEventRepository.
type MockLendingEventRepositoryMockRecorder struct {
	mock *MockLendingEventRepository
}

// NewMockLendingEventRepository creates a new mock instance.
func NewMockLendingEventRepository(ctrl *gomock.Controller) *MockLendingEventRepository {
	mock := &MockLendingEventRepository{ctrl: ctrl}
	mock.recorder = &MockLendingEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLendingEventRepository) EXPECT() *MockLendingEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLendingEventRepository) Create(arg0 context.Context, arg1 *domain.Lending) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLendingEventRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLendingEventRepository)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockLendingEventRepository) FindByID(arg0 context.Context, arg1 ulid.ULID) (*domain.Lending, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Lending)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockLendingEventRepositoryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockLendingEventRepository)(nil).FindByID), arg0, arg1)
}

// FindByUserID mocks base method.
func (m *MockLendingEventRepository) FindByUserID(arg0 context.Context, arg1 uuid.UUID) (*[]domain.Lending, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", arg0, arg1)
	ret0, _ := ret[0].(*[]domain.Lending)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockLendingEventRepositoryMockRecorder) FindByUserID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockLendingEventRepository)(nil).FindByUserID), arg0, arg1)
}

// Update mocks base method.
func (m *MockLendingEventRepository) Update(arg0 context.Context, arg1 *domain.Lending) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLendingEventRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLendingEventRepository)(nil).Update), arg0, arg1)
}
