// Code generated by MockGen. DO NOT EDIT.
// Source: internal/presentation/api/handler/lendingEvent.go
//
// Generated by this command:
//
//	mockgen -source=internal/presentation/api/handler/lendingEvent.go -destination=internal/presentation/api/handler/test/mockLendingUseCase.gen.go -package=handler_test
//

// Package handler_test is a generated GoMock package.
package handler_test

import (
	reflect "reflect"

	handler "github.com/haebeal/datti/internal/presentation/api/handler"
	gomock "go.uber.org/mock/gomock"
)

// MockLendingUseCase is a mock of LendingUseCase interface.
type MockLendingUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLendingUseCaseMockRecorder
	isgomock struct{}
}

// MockLendingUseCaseMockRecorder is the mock recorder for MockLendingUseCase.
type MockLendingUseCaseMockRecorder struct {
	mock *MockLendingUseCase
}

// NewMockLendingUseCase creates a new mock instance.
func NewMockLendingUseCase(ctrl *gomock.Controller) *MockLendingUseCase {
	mock := &MockLendingUseCase{ctrl: ctrl}
	mock.recorder = &MockLendingUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLendingUseCase) EXPECT() *MockLendingUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLendingUseCase) Create(arg0 handler.CreateInput) (*handler.CreateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*handler.CreateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLendingUseCaseMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLendingUseCase)(nil).Create), arg0)
}

// Get mocks base method.
func (m *MockLendingUseCase) Get(arg0 handler.GetInput) (*handler.GetOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*handler.GetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLendingUseCaseMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLendingUseCase)(nil).Get), arg0)
}
