// Code generated by ent, DO NOT EDIT.

package bankaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/datti-api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContainsFold(FieldID, id))
}

// AccountCode applies equality check predicate on the "account_code" field. It's identical to AccountCodeEQ.
func AccountCode(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldAccountCode, v))
}

// BankCode applies equality check predicate on the "bank_code" field. It's identical to BankCodeEQ.
func BankCode(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldBankCode, v))
}

// BranchCode applies equality check predicate on the "branch_code" field. It's identical to BranchCodeEQ.
func BranchCode(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldBranchCode, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// AccountCodeEQ applies the EQ predicate on the "account_code" field.
func AccountCodeEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldAccountCode, v))
}

// AccountCodeNEQ applies the NEQ predicate on the "account_code" field.
func AccountCodeNEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldAccountCode, v))
}

// AccountCodeIn applies the In predicate on the "account_code" field.
func AccountCodeIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldAccountCode, vs...))
}

// AccountCodeNotIn applies the NotIn predicate on the "account_code" field.
func AccountCodeNotIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldAccountCode, vs...))
}

// AccountCodeGT applies the GT predicate on the "account_code" field.
func AccountCodeGT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldAccountCode, v))
}

// AccountCodeGTE applies the GTE predicate on the "account_code" field.
func AccountCodeGTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldAccountCode, v))
}

// AccountCodeLT applies the LT predicate on the "account_code" field.
func AccountCodeLT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldAccountCode, v))
}

// AccountCodeLTE applies the LTE predicate on the "account_code" field.
func AccountCodeLTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldAccountCode, v))
}

// AccountCodeContains applies the Contains predicate on the "account_code" field.
func AccountCodeContains(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContains(FieldAccountCode, v))
}

// AccountCodeHasPrefix applies the HasPrefix predicate on the "account_code" field.
func AccountCodeHasPrefix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasPrefix(FieldAccountCode, v))
}

// AccountCodeHasSuffix applies the HasSuffix predicate on the "account_code" field.
func AccountCodeHasSuffix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasSuffix(FieldAccountCode, v))
}

// AccountCodeEqualFold applies the EqualFold predicate on the "account_code" field.
func AccountCodeEqualFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEqualFold(FieldAccountCode, v))
}

// AccountCodeContainsFold applies the ContainsFold predicate on the "account_code" field.
func AccountCodeContainsFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContainsFold(FieldAccountCode, v))
}

// BankCodeEQ applies the EQ predicate on the "bank_code" field.
func BankCodeEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldBankCode, v))
}

// BankCodeNEQ applies the NEQ predicate on the "bank_code" field.
func BankCodeNEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldBankCode, v))
}

// BankCodeIn applies the In predicate on the "bank_code" field.
func BankCodeIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldBankCode, vs...))
}

// BankCodeNotIn applies the NotIn predicate on the "bank_code" field.
func BankCodeNotIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldBankCode, vs...))
}

// BankCodeGT applies the GT predicate on the "bank_code" field.
func BankCodeGT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldBankCode, v))
}

// BankCodeGTE applies the GTE predicate on the "bank_code" field.
func BankCodeGTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldBankCode, v))
}

// BankCodeLT applies the LT predicate on the "bank_code" field.
func BankCodeLT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldBankCode, v))
}

// BankCodeLTE applies the LTE predicate on the "bank_code" field.
func BankCodeLTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldBankCode, v))
}

// BankCodeContains applies the Contains predicate on the "bank_code" field.
func BankCodeContains(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContains(FieldBankCode, v))
}

// BankCodeHasPrefix applies the HasPrefix predicate on the "bank_code" field.
func BankCodeHasPrefix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasPrefix(FieldBankCode, v))
}

// BankCodeHasSuffix applies the HasSuffix predicate on the "bank_code" field.
func BankCodeHasSuffix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasSuffix(FieldBankCode, v))
}

// BankCodeEqualFold applies the EqualFold predicate on the "bank_code" field.
func BankCodeEqualFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEqualFold(FieldBankCode, v))
}

// BankCodeContainsFold applies the ContainsFold predicate on the "bank_code" field.
func BankCodeContainsFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContainsFold(FieldBankCode, v))
}

// BranchCodeEQ applies the EQ predicate on the "branch_code" field.
func BranchCodeEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldBranchCode, v))
}

// BranchCodeNEQ applies the NEQ predicate on the "branch_code" field.
func BranchCodeNEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldBranchCode, v))
}

// BranchCodeIn applies the In predicate on the "branch_code" field.
func BranchCodeIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldBranchCode, vs...))
}

// BranchCodeNotIn applies the NotIn predicate on the "branch_code" field.
func BranchCodeNotIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldBranchCode, vs...))
}

// BranchCodeGT applies the GT predicate on the "branch_code" field.
func BranchCodeGT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldBranchCode, v))
}

// BranchCodeGTE applies the GTE predicate on the "branch_code" field.
func BranchCodeGTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldBranchCode, v))
}

// BranchCodeLT applies the LT predicate on the "branch_code" field.
func BranchCodeLT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldBranchCode, v))
}

// BranchCodeLTE applies the LTE predicate on the "branch_code" field.
func BranchCodeLTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldBranchCode, v))
}

// BranchCodeContains applies the Contains predicate on the "branch_code" field.
func BranchCodeContains(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContains(FieldBranchCode, v))
}

// BranchCodeHasPrefix applies the HasPrefix predicate on the "branch_code" field.
func BranchCodeHasPrefix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasPrefix(FieldBranchCode, v))
}

// BranchCodeHasSuffix applies the HasSuffix predicate on the "branch_code" field.
func BranchCodeHasSuffix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasSuffix(FieldBranchCode, v))
}

// BranchCodeEqualFold applies the EqualFold predicate on the "branch_code" field.
func BranchCodeEqualFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEqualFold(FieldBranchCode, v))
}

// BranchCodeContainsFold applies the ContainsFold predicate on the "branch_code" field.
func BranchCodeContainsFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContainsFold(FieldBranchCode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BankAccount) predicate.BankAccount {
	return predicate.BankAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BankAccount) predicate.BankAccount {
	return predicate.BankAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BankAccount) predicate.BankAccount {
	return predicate.BankAccount(sql.NotPredicates(p))
}
