services:
  app:
    container_name: datti
    image: "mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm"
    environment:
      - TZ=Asia/Tokyo
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /workspace/datti
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: atlas_db
      TZ: Asia/Tokyo
    volumes:
      - type: bind
        source: ./db/data
        target: /var/lib/postgresql/data
