# イメージを指定
FROM mcr.microsoft.com/devcontainers/go:1-1.22-bookworm

# 環境変数の指定
ENV TZ=Asia/Tokyo

# 追加の依存関係をインストール
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# ワーキングディレクトリの指定
WORKDIR /workspace

# ワーキングディレクトリにコピー
COPY . /workspace

# 依存関係の整理
RUN go mod tidy
