// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datti-api/ent/bankaccount"
)

// BankAccountCreate is the builder for creating a BankAccount entity.
type BankAccountCreate struct {
	config
	mutation *BankAccountMutation
	hooks    []Hook
}

// SetAccountCode sets the "account_code" field.
func (bac *BankAccountCreate) SetAccountCode(s string) *BankAccountCreate {
	bac.mutation.SetAccountCode(s)
	return bac
}

// SetBankCode sets the "bank_code" field.
func (bac *BankAccountCreate) SetBankCode(s string) *BankAccountCreate {
	bac.mutation.SetBankCode(s)
	return bac
}

// SetBranchCode sets the "branch_code" field.
func (bac *BankAccountCreate) SetBranchCode(s string) *BankAccountCreate {
	bac.mutation.SetBranchCode(s)
	return bac
}

// SetCreateAt sets the "create_at" field.
func (bac *BankAccountCreate) SetCreateAt(t time.Time) *BankAccountCreate {
	bac.mutation.SetCreateAt(t)
	return bac
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (bac *BankAccountCreate) SetNillableCreateAt(t *time.Time) *BankAccountCreate {
	if t != nil {
		bac.SetCreateAt(*t)
	}
	return bac
}

// SetUpdateAt sets the "update_at" field.
func (bac *BankAccountCreate) SetUpdateAt(t time.Time) *BankAccountCreate {
	bac.mutation.SetUpdateAt(t)
	return bac
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (bac *BankAccountCreate) SetNillableUpdateAt(t *time.Time) *BankAccountCreate {
	if t != nil {
		bac.SetUpdateAt(*t)
	}
	return bac
}

// SetDeleteAt sets the "delete_at" field.
func (bac *BankAccountCreate) SetDeleteAt(t time.Time) *BankAccountCreate {
	bac.mutation.SetDeleteAt(t)
	return bac
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (bac *BankAccountCreate) SetNillableDeleteAt(t *time.Time) *BankAccountCreate {
	if t != nil {
		bac.SetDeleteAt(*t)
	}
	return bac
}

// SetID sets the "id" field.
func (bac *BankAccountCreate) SetID(s string) *BankAccountCreate {
	bac.mutation.SetID(s)
	return bac
}

// Mutation returns the BankAccountMutation object of the builder.
func (bac *BankAccountCreate) Mutation() *BankAccountMutation {
	return bac.mutation
}

// Save creates the BankAccount in the database.
func (bac *BankAccountCreate) Save(ctx context.Context) (*BankAccount, error) {
	bac.defaults()
	return withHooks(ctx, bac.sqlSave, bac.mutation, bac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bac *BankAccountCreate) SaveX(ctx context.Context) *BankAccount {
	v, err := bac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bac *BankAccountCreate) Exec(ctx context.Context) error {
	_, err := bac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bac *BankAccountCreate) ExecX(ctx context.Context) {
	if err := bac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bac *BankAccountCreate) defaults() {
	if _, ok := bac.mutation.CreateAt(); !ok {
		v := bankaccount.DefaultCreateAt()
		bac.mutation.SetCreateAt(v)
	}
	if _, ok := bac.mutation.UpdateAt(); !ok {
		v := bankaccount.DefaultUpdateAt()
		bac.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bac *BankAccountCreate) check() error {
	if _, ok := bac.mutation.AccountCode(); !ok {
		return &ValidationError{Name: "account_code", err: errors.New(`ent: missing required field "BankAccount.account_code"`)}
	}
	if v, ok := bac.mutation.AccountCode(); ok {
		if err := bankaccount.AccountCodeValidator(v); err != nil {
			return &ValidationError{Name: "account_code", err: fmt.Errorf(`ent: validator failed for field "BankAccount.account_code": %w`, err)}
		}
	}
	if _, ok := bac.mutation.BankCode(); !ok {
		return &ValidationError{Name: "bank_code", err: errors.New(`ent: missing required field "BankAccount.bank_code"`)}
	}
	if v, ok := bac.mutation.BankCode(); ok {
		if err := bankaccount.BankCodeValidator(v); err != nil {
			return &ValidationError{Name: "bank_code", err: fmt.Errorf(`ent: validator failed for field "BankAccount.bank_code": %w`, err)}
		}
	}
	if _, ok := bac.mutation.BranchCode(); !ok {
		return &ValidationError{Name: "branch_code", err: errors.New(`ent: missing required field "BankAccount.branch_code"`)}
	}
	if v, ok := bac.mutation.BranchCode(); ok {
		if err := bankaccount.BranchCodeValidator(v); err != nil {
			return &ValidationError{Name: "branch_code", err: fmt.Errorf(`ent: validator failed for field "BankAccount.branch_code": %w`, err)}
		}
	}
	if _, ok := bac.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "BankAccount.create_at"`)}
	}
	if _, ok := bac.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New(`ent: missing required field "BankAccount.update_at"`)}
	}
	if v, ok := bac.mutation.ID(); ok {
		if err := bankaccount.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "BankAccount.id": %w`, err)}
		}
	}
	return nil
}

func (bac *BankAccountCreate) sqlSave(ctx context.Context) (*BankAccount, error) {
	if err := bac.check(); err != nil {
		return nil, err
	}
	_node, _spec := bac.createSpec()
	if err := sqlgraph.CreateNode(ctx, bac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BankAccount.ID type: %T", _spec.ID.Value)
		}
	}
	bac.mutation.id = &_node.ID
	bac.mutation.done = true
	return _node, nil
}

func (bac *BankAccountCreate) createSpec() (*BankAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &BankAccount{config: bac.config}
		_spec = sqlgraph.NewCreateSpec(bankaccount.Table, sqlgraph.NewFieldSpec(bankaccount.FieldID, field.TypeString))
	)
	if id, ok := bac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bac.mutation.AccountCode(); ok {
		_spec.SetField(bankaccount.FieldAccountCode, field.TypeString, value)
		_node.AccountCode = value
	}
	if value, ok := bac.mutation.BankCode(); ok {
		_spec.SetField(bankaccount.FieldBankCode, field.TypeString, value)
		_node.BankCode = value
	}
	if value, ok := bac.mutation.BranchCode(); ok {
		_spec.SetField(bankaccount.FieldBranchCode, field.TypeString, value)
		_node.BranchCode = value
	}
	if value, ok := bac.mutation.CreateAt(); ok {
		_spec.SetField(bankaccount.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := bac.mutation.UpdateAt(); ok {
		_spec.SetField(bankaccount.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	if value, ok := bac.mutation.DeleteAt(); ok {
		_spec.SetField(bankaccount.FieldDeleteAt, field.TypeTime, value)
		_node.DeleteAt = &value
	}
	return _node, _spec
}

// BankAccountCreateBulk is the builder for creating many BankAccount entities in bulk.
type BankAccountCreateBulk struct {
	config
	err      error
	builders []*BankAccountCreate
}

// Save creates the BankAccount entities in the database.
func (bacb *BankAccountCreateBulk) Save(ctx context.Context) ([]*BankAccount, error) {
	if bacb.err != nil {
		return nil, bacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bacb.builders))
	nodes := make([]*BankAccount, len(bacb.builders))
	mutators := make([]Mutator, len(bacb.builders))
	for i := range bacb.builders {
		func(i int, root context.Context) {
			builder := bacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BankAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bacb *BankAccountCreateBulk) SaveX(ctx context.Context) []*BankAccount {
	v, err := bacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bacb *BankAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := bacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bacb *BankAccountCreateBulk) ExecX(ctx context.Context) {
	if err := bacb.Exec(ctx); err != nil {
		panic(err)
	}
}
