// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datti-api/ent/friend"
)

// FriendCreate is the builder for creating a Friend entity.
type FriendCreate struct {
	config
	mutation *FriendMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (fc *FriendCreate) SetUID(s string) *FriendCreate {
	fc.mutation.SetUID(s)
	return fc
}

// SetFriendUID sets the "friend_uid" field.
func (fc *FriendCreate) SetFriendUID(s string) *FriendCreate {
	fc.mutation.SetFriendUID(s)
	return fc
}

// SetCreatedAt sets the "created_at" field.
func (fc *FriendCreate) SetCreatedAt(t time.Time) *FriendCreate {
	fc.mutation.SetCreatedAt(t)
	return fc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fc *FriendCreate) SetNillableCreatedAt(t *time.Time) *FriendCreate {
	if t != nil {
		fc.SetCreatedAt(*t)
	}
	return fc
}

// SetUpdatedAt sets the "updated_at" field.
func (fc *FriendCreate) SetUpdatedAt(t time.Time) *FriendCreate {
	fc.mutation.SetUpdatedAt(t)
	return fc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fc *FriendCreate) SetNillableUpdatedAt(t *time.Time) *FriendCreate {
	if t != nil {
		fc.SetUpdatedAt(*t)
	}
	return fc
}

// SetDeletedAt sets the "deleted_at" field.
func (fc *FriendCreate) SetDeletedAt(t time.Time) *FriendCreate {
	fc.mutation.SetDeletedAt(t)
	return fc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fc *FriendCreate) SetNillableDeletedAt(t *time.Time) *FriendCreate {
	if t != nil {
		fc.SetDeletedAt(*t)
	}
	return fc
}

// Mutation returns the FriendMutation object of the builder.
func (fc *FriendCreate) Mutation() *FriendMutation {
	return fc.mutation
}

// Save creates the Friend in the database.
func (fc *FriendCreate) Save(ctx context.Context) (*Friend, error) {
	fc.defaults()
	return withHooks(ctx, fc.sqlSave, fc.mutation, fc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FriendCreate) SaveX(ctx context.Context) *Friend {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FriendCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FriendCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fc *FriendCreate) defaults() {
	if _, ok := fc.mutation.CreatedAt(); !ok {
		v := friend.DefaultCreatedAt()
		fc.mutation.SetCreatedAt(v)
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		v := friend.DefaultUpdatedAt()
		fc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FriendCreate) check() error {
	if _, ok := fc.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "Friend.uid"`)}
	}
	if v, ok := fc.mutation.UID(); ok {
		if err := friend.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "Friend.uid": %w`, err)}
		}
	}
	if _, ok := fc.mutation.FriendUID(); !ok {
		return &ValidationError{Name: "friend_uid", err: errors.New(`ent: missing required field "Friend.friend_uid"`)}
	}
	if v, ok := fc.mutation.FriendUID(); ok {
		if err := friend.FriendUIDValidator(v); err != nil {
			return &ValidationError{Name: "friend_uid", err: fmt.Errorf(`ent: validator failed for field "Friend.friend_uid": %w`, err)}
		}
	}
	if _, ok := fc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Friend.created_at"`)}
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Friend.updated_at"`)}
	}
	return nil
}

func (fc *FriendCreate) sqlSave(ctx context.Context) (*Friend, error) {
	if err := fc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	fc.mutation.id = &_node.ID
	fc.mutation.done = true
	return _node, nil
}

func (fc *FriendCreate) createSpec() (*Friend, *sqlgraph.CreateSpec) {
	var (
		_node = &Friend{config: fc.config}
		_spec = sqlgraph.NewCreateSpec(friend.Table, sqlgraph.NewFieldSpec(friend.FieldID, field.TypeInt))
	)
	if value, ok := fc.mutation.UID(); ok {
		_spec.SetField(friend.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := fc.mutation.FriendUID(); ok {
		_spec.SetField(friend.FieldFriendUID, field.TypeString, value)
		_node.FriendUID = value
	}
	if value, ok := fc.mutation.CreatedAt(); ok {
		_spec.SetField(friend.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := fc.mutation.UpdatedAt(); ok {
		_spec.SetField(friend.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := fc.mutation.DeletedAt(); ok {
		_spec.SetField(friend.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// FriendCreateBulk is the builder for creating many Friend entities in bulk.
type FriendCreateBulk struct {
	config
	err      error
	builders []*FriendCreate
}

// Save creates the Friend entities in the database.
func (fcb *FriendCreateBulk) Save(ctx context.Context) ([]*Friend, error) {
	if fcb.err != nil {
		return nil, fcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Friend, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FriendMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FriendCreateBulk) SaveX(ctx context.Context) []*Friend {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FriendCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FriendCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
