// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datti-api/ent/groupuser"
)

// GroupUserCreate is the builder for creating a GroupUser entity.
type GroupUserCreate struct {
	config
	mutation *GroupUserMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (guc *GroupUserCreate) SetUID(s string) *GroupUserCreate {
	guc.mutation.SetUID(s)
	return guc
}

// SetGroupID sets the "group_id" field.
func (guc *GroupUserCreate) SetGroupID(s string) *GroupUserCreate {
	guc.mutation.SetGroupID(s)
	return guc
}

// SetOwner sets the "owner" field.
func (guc *GroupUserCreate) SetOwner(b bool) *GroupUserCreate {
	guc.mutation.SetOwner(b)
	return guc
}

// SetCreateAt sets the "create_at" field.
func (guc *GroupUserCreate) SetCreateAt(t time.Time) *GroupUserCreate {
	guc.mutation.SetCreateAt(t)
	return guc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (guc *GroupUserCreate) SetNillableCreateAt(t *time.Time) *GroupUserCreate {
	if t != nil {
		guc.SetCreateAt(*t)
	}
	return guc
}

// SetUpdateAt sets the "update_at" field.
func (guc *GroupUserCreate) SetUpdateAt(t time.Time) *GroupUserCreate {
	guc.mutation.SetUpdateAt(t)
	return guc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (guc *GroupUserCreate) SetNillableUpdateAt(t *time.Time) *GroupUserCreate {
	if t != nil {
		guc.SetUpdateAt(*t)
	}
	return guc
}

// SetDeleteAt sets the "delete_at" field.
func (guc *GroupUserCreate) SetDeleteAt(t time.Time) *GroupUserCreate {
	guc.mutation.SetDeleteAt(t)
	return guc
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (guc *GroupUserCreate) SetNillableDeleteAt(t *time.Time) *GroupUserCreate {
	if t != nil {
		guc.SetDeleteAt(*t)
	}
	return guc
}

// Mutation returns the GroupUserMutation object of the builder.
func (guc *GroupUserCreate) Mutation() *GroupUserMutation {
	return guc.mutation
}

// Save creates the GroupUser in the database.
func (guc *GroupUserCreate) Save(ctx context.Context) (*GroupUser, error) {
	guc.defaults()
	return withHooks(ctx, guc.sqlSave, guc.mutation, guc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (guc *GroupUserCreate) SaveX(ctx context.Context) *GroupUser {
	v, err := guc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (guc *GroupUserCreate) Exec(ctx context.Context) error {
	_, err := guc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guc *GroupUserCreate) ExecX(ctx context.Context) {
	if err := guc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (guc *GroupUserCreate) defaults() {
	if _, ok := guc.mutation.CreateAt(); !ok {
		v := groupuser.DefaultCreateAt()
		guc.mutation.SetCreateAt(v)
	}
	if _, ok := guc.mutation.UpdateAt(); !ok {
		v := groupuser.DefaultUpdateAt()
		guc.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (guc *GroupUserCreate) check() error {
	if _, ok := guc.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "GroupUser.uid"`)}
	}
	if v, ok := guc.mutation.UID(); ok {
		if err := groupuser.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "GroupUser.uid": %w`, err)}
		}
	}
	if _, ok := guc.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupUser.group_id"`)}
	}
	if v, ok := guc.mutation.GroupID(); ok {
		if err := groupuser.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "GroupUser.group_id": %w`, err)}
		}
	}
	if _, ok := guc.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "GroupUser.owner"`)}
	}
	if _, ok := guc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "GroupUser.create_at"`)}
	}
	if _, ok := guc.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New(`ent: missing required field "GroupUser.update_at"`)}
	}
	return nil
}

func (guc *GroupUserCreate) sqlSave(ctx context.Context) (*GroupUser, error) {
	if err := guc.check(); err != nil {
		return nil, err
	}
	_node, _spec := guc.createSpec()
	if err := sqlgraph.CreateNode(ctx, guc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	guc.mutation.id = &_node.ID
	guc.mutation.done = true
	return _node, nil
}

func (guc *GroupUserCreate) createSpec() (*GroupUser, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupUser{config: guc.config}
		_spec = sqlgraph.NewCreateSpec(groupuser.Table, sqlgraph.NewFieldSpec(groupuser.FieldID, field.TypeInt))
	)
	if value, ok := guc.mutation.UID(); ok {
		_spec.SetField(groupuser.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := guc.mutation.GroupID(); ok {
		_spec.SetField(groupuser.FieldGroupID, field.TypeString, value)
		_node.GroupID = value
	}
	if value, ok := guc.mutation.Owner(); ok {
		_spec.SetField(groupuser.FieldOwner, field.TypeBool, value)
		_node.Owner = value
	}
	if value, ok := guc.mutation.CreateAt(); ok {
		_spec.SetField(groupuser.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := guc.mutation.UpdateAt(); ok {
		_spec.SetField(groupuser.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	if value, ok := guc.mutation.DeleteAt(); ok {
		_spec.SetField(groupuser.FieldDeleteAt, field.TypeTime, value)
		_node.DeleteAt = &value
	}
	return _node, _spec
}

// GroupUserCreateBulk is the builder for creating many GroupUser entities in bulk.
type GroupUserCreateBulk struct {
	config
	err      error
	builders []*GroupUserCreate
}

// Save creates the GroupUser entities in the database.
func (gucb *GroupUserCreateBulk) Save(ctx context.Context) ([]*GroupUser, error) {
	if gucb.err != nil {
		return nil, gucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gucb.builders))
	nodes := make([]*GroupUser, len(gucb.builders))
	mutators := make([]Mutator, len(gucb.builders))
	for i := range gucb.builders {
		func(i int, root context.Context) {
			builder := gucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gucb *GroupUserCreateBulk) SaveX(ctx context.Context) []*GroupUser {
	v, err := gucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gucb *GroupUserCreateBulk) Exec(ctx context.Context) error {
	_, err := gucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gucb *GroupUserCreateBulk) ExecX(ctx context.Context) {
	if err := gucb.Exec(ctx); err != nil {
		panic(err)
	}
}
