// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Debtor 債務者
type Debtor struct {
	Amount uint64 `json:"amount"`

	// User ユーザー
	User User `json:"user"`
}

// Payer 債権者
type Payer struct {
	Amount uint64 `json:"amount"`

	// User ユーザー
	User User `json:"user"`
}

// PaymentEvent defines model for PaymentEvent.
type PaymentEvent struct {
	CreatedAt time.Time `json:"createdAt"`
	Debtors   []Debtor  `json:"debtors"`
	EventDate time.Time `json:"eventDate"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`

	// Payer 債権者
	Payer     Payer     `json:"payer"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// User ユーザー
type User struct {
	Avater string `json:"avater"`
	Email  string `json:"email"`
	Id     string `json:"id"`
	Name   string `json:"name"`
}

// CreatePaymentEventCreatePaymentEventJSONRequestBody defines body for CreatePaymentEventCreatePaymentEvent for application/json ContentType.
type CreatePaymentEventCreatePaymentEventJSONRequestBody = PaymentEvent
