// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HealthHealthResponseStatus.
const (
	Ok HealthHealthResponseStatus = "ok"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// HealthHealthResponse defines model for Health.HealthResponse.
type HealthHealthResponse struct {
	Status    HealthHealthResponseStatus `json:"status"`
	Timestamp time.Time                  `json:"timestamp"`
}

// HealthHealthResponseStatus defines model for HealthHealthResponse.Status.
type HealthHealthResponseStatus string

// PaymentCreateEventRequest defines model for Payment.CreateEventRequest.
type PaymentCreateEventRequest struct {
	Debtors []struct {
		Amount uint64 `json:"amount"`
		Id     string `json:"id"`
	} `json:"debtors"`
	EventDate time.Time `json:"eventDate"`
	Name      string    `json:"name"`
	Payer     struct {
		Amount uint64 `json:"amount"`
		Id     string `json:"id"`
	} `json:"payer"`
}

// PaymentCreateEventResponse defines model for Payment.CreateEventResponse.
type PaymentCreateEventResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	Debtors   []struct {
		Amount uint64 `json:"amount"`
		Avatar string `json:"avatar"`
		Email  string `json:"email"`
		Id     string `json:"id"`
		Name   string `json:"name"`
	} `json:"debtors"`
	EventDate time.Time `json:"eventDate"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	Payer     struct {
		Amount uint64 `json:"amount"`
		Avatar string `json:"avatar"`
		Email  string `json:"email"`
		Id     string `json:"id"`
		Name   string `json:"name"`
	} `json:"payer"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// PaymentGetEventResponse defines model for Payment.GetEventResponse.
type PaymentGetEventResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	Debtors   []struct {
		Amount uint64 `json:"amount"`
		Avatar string `json:"avatar"`
		Email  string `json:"email"`
		Id     string `json:"id"`
		Name   string `json:"name"`
	} `json:"debtors"`
	EventDate time.Time `json:"eventDate"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	Payer     struct {
		Amount uint64 `json:"amount"`
		Avatar string `json:"avatar"`
		Email  string `json:"email"`
		Id     string `json:"id"`
		Name   string `json:"name"`
	} `json:"payer"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// PaymentEventCreateJSONRequestBody defines body for PaymentEventCreate for application/json ContentType.
type PaymentEventCreateJSONRequestBody = PaymentCreateEventRequest
