/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedRepaymentsIndexRouteImport } from './routes/_authenticated/repayments/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups/index'
import { Route as AuthenticatedRepaymentsNewRouteImport } from './routes/_authenticated/repayments/new'
import { Route as AuthenticatedProfileConnectRouteImport } from './routes/_authenticated/profile/connect'
import { Route as AuthenticatedProfileAccountRouteImport } from './routes/_authenticated/profile/account'
import { Route as AuthenticatedGroupsNewRouteImport } from './routes/_authenticated/groups/new'
import { Route as AuthenticatedRepaymentsIdIndexRouteImport } from './routes/_authenticated/repayments/$id/index'
import { Route as ApiAuthCognitoCallbackRouteImport } from './routes/api/auth/cognito/callback'
import { Route as AuthenticatedRepaymentsIdEditRouteImport } from './routes/_authenticated/repayments/$id/edit'
import { Route as AuthenticatedGroupsGroupIdLendingsIndexRouteImport } from './routes/_authenticated/groups/$groupId/lendings/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepaymentsIndexRoute =
  AuthenticatedRepaymentsIndexRouteImport.update({
    id: '/repayments/',
    path: '/repayments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AuthenticatedRepaymentsNewRoute =
  AuthenticatedRepaymentsNewRouteImport.update({
    id: '/repayments/new',
    path: '/repayments/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileConnectRoute =
  AuthenticatedProfileConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileAccountRoute =
  AuthenticatedProfileAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedGroupsNewRoute = AuthenticatedGroupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedGroupsRoute,
} as any)
const AuthenticatedRepaymentsIdIndexRoute =
  AuthenticatedRepaymentsIdIndexRouteImport.update({
    id: '/repayments/$id/',
    path: '/repayments/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthCognitoCallbackRoute = ApiAuthCognitoCallbackRouteImport.update({
  id: '/api/auth/cognito/callback',
  path: '/api/auth/cognito/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRepaymentsIdEditRoute =
  AuthenticatedRepaymentsIdEditRouteImport.update({
    id: '/repayments/$id/edit',
    path: '/repayments/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsGroupIdLendingsIndexRoute =
  AuthenticatedGroupsGroupIdLendingsIndexRouteImport.update({
    id: '/$groupId/lendings/',
    path: '/$groupId/lendings/',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/groups/new': typeof AuthenticatedGroupsNewRoute
  '/profile/account': typeof AuthenticatedProfileAccountRoute
  '/profile/connect': typeof AuthenticatedProfileConnectRoute
  '/repayments/new': typeof AuthenticatedRepaymentsNewRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/repayments/': typeof AuthenticatedRepaymentsIndexRoute
  '/repayments/$id/edit': typeof AuthenticatedRepaymentsIdEditRoute
  '/api/auth/cognito/callback': typeof ApiAuthCognitoCallbackRoute
  '/repayments/$id/': typeof AuthenticatedRepaymentsIdIndexRoute
  '/groups/$groupId/lendings/': typeof AuthenticatedGroupsGroupIdLendingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/groups/new': typeof AuthenticatedGroupsNewRoute
  '/profile/account': typeof AuthenticatedProfileAccountRoute
  '/profile/connect': typeof AuthenticatedProfileConnectRoute
  '/repayments/new': typeof AuthenticatedRepaymentsNewRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/repayments': typeof AuthenticatedRepaymentsIndexRoute
  '/repayments/$id/edit': typeof AuthenticatedRepaymentsIdEditRoute
  '/api/auth/cognito/callback': typeof ApiAuthCognitoCallbackRoute
  '/repayments/$id': typeof AuthenticatedRepaymentsIdIndexRoute
  '/groups/$groupId/lendings': typeof AuthenticatedGroupsGroupIdLendingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/groups/new': typeof AuthenticatedGroupsNewRoute
  '/_authenticated/profile/account': typeof AuthenticatedProfileAccountRoute
  '/_authenticated/profile/connect': typeof AuthenticatedProfileConnectRoute
  '/_authenticated/repayments/new': typeof AuthenticatedRepaymentsNewRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/repayments/': typeof AuthenticatedRepaymentsIndexRoute
  '/_authenticated/repayments/$id/edit': typeof AuthenticatedRepaymentsIdEditRoute
  '/api/auth/cognito/callback': typeof ApiAuthCognitoCallbackRoute
  '/_authenticated/repayments/$id/': typeof AuthenticatedRepaymentsIdIndexRoute
  '/_authenticated/groups/$groupId/lendings/': typeof AuthenticatedGroupsGroupIdLendingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/profile'
    | '/auth/'
    | '/groups/new'
    | '/profile/account'
    | '/profile/connect'
    | '/repayments/new'
    | '/groups/'
    | '/profile/'
    | '/repayments/'
    | '/repayments/$id/edit'
    | '/api/auth/cognito/callback'
    | '/repayments/$id/'
    | '/groups/$groupId/lendings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/groups/new'
    | '/profile/account'
    | '/profile/connect'
    | '/repayments/new'
    | '/groups'
    | '/profile'
    | '/repayments'
    | '/repayments/$id/edit'
    | '/api/auth/cognito/callback'
    | '/repayments/$id'
    | '/groups/$groupId/lendings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/groups'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/groups/new'
    | '/_authenticated/profile/account'
    | '/_authenticated/profile/connect'
    | '/_authenticated/repayments/new'
    | '/_authenticated/groups/'
    | '/_authenticated/profile/'
    | '/_authenticated/repayments/'
    | '/_authenticated/repayments/$id/edit'
    | '/api/auth/cognito/callback'
    | '/_authenticated/repayments/$id/'
    | '/_authenticated/groups/$groupId/lendings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  ApiAuthCognitoCallbackRoute: typeof ApiAuthCognitoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repayments/': {
      id: '/_authenticated/repayments/'
      path: '/repayments'
      fullPath: '/repayments/'
      preLoaderRoute: typeof AuthenticatedRepaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/repayments/new': {
      id: '/_authenticated/repayments/new'
      path: '/repayments/new'
      fullPath: '/repayments/new'
      preLoaderRoute: typeof AuthenticatedRepaymentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/connect': {
      id: '/_authenticated/profile/connect'
      path: '/connect'
      fullPath: '/profile/connect'
      preLoaderRoute: typeof AuthenticatedProfileConnectRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/account': {
      id: '/_authenticated/profile/account'
      path: '/account'
      fullPath: '/profile/account'
      preLoaderRoute: typeof AuthenticatedProfileAccountRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/groups/new': {
      id: '/_authenticated/groups/new'
      path: '/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AuthenticatedGroupsNewRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/repayments/$id/': {
      id: '/_authenticated/repayments/$id/'
      path: '/repayments/$id'
      fullPath: '/repayments/$id/'
      preLoaderRoute: typeof AuthenticatedRepaymentsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/cognito/callback': {
      id: '/api/auth/cognito/callback'
      path: '/api/auth/cognito/callback'
      fullPath: '/api/auth/cognito/callback'
      preLoaderRoute: typeof ApiAuthCognitoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/repayments/$id/edit': {
      id: '/_authenticated/repayments/$id/edit'
      path: '/repayments/$id/edit'
      fullPath: '/repayments/$id/edit'
      preLoaderRoute: typeof AuthenticatedRepaymentsIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$groupId/lendings/': {
      id: '/_authenticated/groups/$groupId/lendings/'
      path: '/$groupId/lendings'
      fullPath: '/groups/$groupId/lendings/'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdLendingsIndexRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
  }
}

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsNewRoute: typeof AuthenticatedGroupsNewRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedGroupsGroupIdLendingsIndexRoute: typeof AuthenticatedGroupsGroupIdLendingsIndexRoute
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsNewRoute: AuthenticatedGroupsNewRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedGroupsGroupIdLendingsIndexRoute:
    AuthenticatedGroupsGroupIdLendingsIndexRoute,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileAccountRoute: typeof AuthenticatedProfileAccountRoute
  AuthenticatedProfileConnectRoute: typeof AuthenticatedProfileConnectRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileAccountRoute: AuthenticatedProfileAccountRoute,
  AuthenticatedProfileConnectRoute: AuthenticatedProfileConnectRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRepaymentsNewRoute: typeof AuthenticatedRepaymentsNewRoute
  AuthenticatedRepaymentsIndexRoute: typeof AuthenticatedRepaymentsIndexRoute
  AuthenticatedRepaymentsIdEditRoute: typeof AuthenticatedRepaymentsIdEditRoute
  AuthenticatedRepaymentsIdIndexRoute: typeof AuthenticatedRepaymentsIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRepaymentsNewRoute: AuthenticatedRepaymentsNewRoute,
  AuthenticatedRepaymentsIndexRoute: AuthenticatedRepaymentsIndexRoute,
  AuthenticatedRepaymentsIdEditRoute: AuthenticatedRepaymentsIdEditRoute,
  AuthenticatedRepaymentsIdIndexRoute: AuthenticatedRepaymentsIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthCognitoCallbackRoute: ApiAuthCognitoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
