name: Build and Deploy to Fly.io

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: デプロイ先環境名(基本的にprod, devのいずれかを使用)
      ref:
        type: string
        required: true
        description: コミットID(SHA)

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Authenticate with Fly.io Docker Registry
        run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./dockerfile  # Dockerfile のパスを指定
          push: true
          tags: registry.fly.io/${{ vars.FLY_APP_NAME }} # ビルドしたイメージを指定

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --local-only --debug --config ${{ vars.FLY_CONFIG_PATH }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}

