# Webのデプロイを行うWorkflow
name: deploy:web

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - app/web/app
      - .github/workflows/deploy:web.yml

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: app/web/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci
  deploy:
    needs: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Restore node_modules
        id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: app/web/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Build Artifacts
        run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: datti-web
          workingDirectory: app/web
          directory: ./build/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Add publish URL as commit status
        uses: actions/github-script@v6
        with:
          script: |
            const sha = context.payload.pull_request?.head.sha ?? context.sha;
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              context: 'Cloudflare Pages',
              description: 'Cloudflare Pages deployment',
              state: 'success',
              sha,
              target_url: "${{ steps.cloudflare_pages_deploy.outputs.url }}",
            });
