// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BankAccount is the predicate function for bankaccount builders.
type BankAccount func(*sql.Selector)

// Friend is the predicate function for friend builders.
type Friend func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupUser is the predicate function for groupuser builders.
type GroupUser func(*sql.Selector)
